- name: Install nmap
  hosts: all
  become: true

  tasks:
    - name: Install nmap on Ubuntu/Debian
      apt:
        name: nmap
        state: present
        update_cache: true
      when: ansible_facts['os_family']=="Debian"
    - name: Install nmap on CentOS/HedHat
      yum:
        name: nmap
        state: present
      when: ansible_facts['os_family']=="RedHat"

  