- name: Install iperf
  hosts: all
  become: true

  tasks:
    - name: Install iperf on Ubuntu/Debian
      ansible.builtin.apt:
        name: iperf
        state: present
        update_cache: true
      when: ansible_facts.os_family=="Debian"
    - name: Install iperf on CentOS/RedHat
      ansible.builtin.dnf:
        name: iperf
        state: present
      when: ansible_facts.os_family =="RedHat"
