---
- name: Copy scheduled tasks between Windows servers
  hosts: windows_servers
  roles:
    - role: ../roles/win_scheduledTask_copy
      vars:
        source_server: "{{ source_server | trim }}"
        source_directory: "{{ source_directory | trim }}"
        destination_servers: "{{ destination_servers | split(',') | map('trim') | list }}"
        destination_directory: "{{ destination_directory | trim }}"
        tasks_to_copy: "{{ tasks_to_copy | split(',') | map('trim') | list }}"